# Generated by Django 6.0.7 on 2026-07-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('service_needed', models.CharField(choices=[('manual', 'Manual Testing'), ('automation_web', 'Web Automation (Selenium)'), ('automation_mobile', 'Mobile Automation (Appium)'), ('api', 'API Testing'), ('device', 'Device / IoT / VoIP Testing'), ('framework', 'Automation Framework Setup'), ('other', 'Other')], default='other', max_length=30)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
