# Generated by Django 6.0.7 on 2026-07-31 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="The question visitors typically ask, e.g. 'Do you test iOS apps?'", max_length=255)),
                ('keywords', models.CharField(blank=True, help_text="Optional comma-separated synonyms/keywords to widen matching, e.g. 'ios, iphone, apple, xcode'", max_length=255)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to keep a draft answer out of the live bot/FAQ.')),
                ('times_matched', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Knowledge base',
                'ordering': ['-times_matched', 'question'],
            },
        ),
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('answer_given', models.TextField(blank=True)),
                ('needs_answer', models.BooleanField(default=True)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_kb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='chatbot.knowledgebase')),
            ],
            options={
                'verbose_name_plural': 'Chat queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
